# Generated by Django 5.0.6 on 2024-06-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("boardId", models.AutoField(primary_key=True, serialize=False)),
                ("boardTitle", models.CharField(max_length=128)),
                ("boardWriter", models.CharField(max_length=32)),
                ("boardContent", models.TextField()),
                ("boardImage", models.CharField(max_length=100, null=True)),
                ("boardRegDate", models.DateTimeField(auto_now_add=True)),
                ("boardUpdDate", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "board",
            },
        ),
    ]
