# Generated by Django 5.0.6 on 2024-07-03 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("reviewId", models.AutoField(primary_key=True, serialize=False)),
                ("reviewTitle", models.CharField(max_length=128)),
                ("reviewWriter", models.CharField(max_length=32)),
                ("reviewContent", models.TextField()),
                (
                    "reviewRating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("reviewImage", models.CharField(max_length=100, null=True)),
                ("reviewRegDate", models.DateTimeField(auto_now_add=True)),
                ("reviewUpdDate", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "db_table": "review",
            },
        ),
    ]
