# Generated by Django 5.0.6 on 2024-07-03 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersitem",
            name="quantity",
        ),
    ]
